### ISSUE TITLE
[ch06] トップページの「予定の追加」を選択するとエラーが発生する

### ISSUE THREAD

**Issue by yui15** [yui15/nano_planner#1]
エラーログは以下の通り。
```
** (UndefinedFunctionError) function NanoPlannerWeb.PlanItemView.render/2 is undefined (module NanoPlannerWeb.PlanItemView is not available)
        NanoPlannerWeb.PlanItemView.render("new.html", %{changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #NanoPlanner.Schedule.PlanItem<>, valid?: true>, conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #NanoPlanner.Schedule.PlanItem<>, valid?: true>, layout: {NanoPlannerWeb.LayoutView, "app.html"}}, body_params: %{}, cookies: %{}, halted: false, host: "localhost", method: "GET", owner: #PID<0.590.0>, params: %{}, path_info: ["plan_items", "new"], path_params: %{}, port: 4000, private: %{NanoPlannerWeb.Router => {[], %{}}, :before_send => [#Function<0.126912816/1 in Plug.CSRFProtection.call/2>, #Function<2.41720411/1 in Phoenix.Controller.fetch_flash/2>, #Function<0.123471702/1 in Plug.Session.before_send/2>, #Function<0.11227428/1 in Plug.Telemetry.call/2>, #Function<1.131228478/1 in Phoenix.LiveReloader.before_send_inject_reloader/3>], :phoenix_action => :new, :phoenix_controller => NanoPlannerWeb.PlanItemController, :phoenix_endpoint => NanoPlannerWeb.Endpoint, :phoenix_flash => %{}, :phoenix_format => "html", :phoenix_layout => {NanoPlannerWeb.LayoutView, :app}, :phoenix_request_logger => {"request_logger", "request_logger"}, :phoenix_router => NanoPlannerWeb.Router, :phoenix_template => "new.html", :phoenix_view => NanoPlannerWeb.PlanItemView, :plug_session => %{}, :plug_session_fetch => :done}, query_params: %{}, query_string: "", remote_ip: {172, 21, 0, 1}, req_cookies: %{}, req_headers: [{"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "ja,en-US;q=0.9,en;q=0.8"}, {"connection", "keep-alive"}, {"host", "localhost:4000"}, {"referer", "http://localhost:4000/"}, {"sec-ch-ua", "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Google Chrome\";v=\"116\""}, {"sec-ch-ua-mobile", "?0"}, {"sec-ch-ua-platform", "\"Windows\""}, {"sec-fetch-dest", "document"}, {"sec-fetch-mode", "navigate"}, {"sec-fetch-site", "same-origin"}, {"sec-fetch-user", "?1"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"}], request_path: "/plan_items/new", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "F4PEPl4C2pNHz4wAAADF"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"x-content-type-options", "nosniff"}, {"x-download-options", "noopen"}, {"x-permitted-cross-domain-policies", "none"}, {"cross-origin-window-policy", "deny"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, view_module: NanoPlannerWeb.PlanItemView, view_template: "new.html"})
        (phoenix 1.5.14) lib/phoenix/view.ex:310: Phoenix.View.render_within/3
        (phoenix 1.5.14) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
        (nano_planner 0.1.0) lib/nano_planner_web/controllers/plan_item_controller.ex:1: NanoPlannerWeb.PlanItemController.action/2
        (nano_planner 0.1.0) lib/nano_planner_web/controllers/plan_item_controller.ex:1: NanoPlannerWeb.PlanItemController.phoenix_controller_pipeline/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```

**Comment by yui15** [comment]
エラーメッセージにある
```
(nano_planner 0.1.0) lib/nano_planner_web/controllers/plan_item_controller.ex:1: NanoPlannerWeb.PlanItemController.action/2
(nano_planner 0.1.0) lib/nano_planner_web/controllers/plan_item_controller.ex:1:　NanoPlannerWeb.PlanItemController.phoenix_controller_pipeline/2
```
を参照してみたが、`NanoPlannerWeb.PlanItemController.action/2` も `NanoPlannerWeb.PlanItemController.phoenix_controller_pipeline/2` ない。

**Comment by yui15** [comment]
また、エラーメッセージにある
```
** (UndefinedFunctionError) function NanoPlannerWeb.PlanItemView.render/2 is undefined (module NanoPlannerWeb.PlanItemView is not available)
```
に書いてある `render` は、上のコメントのファイルにある `render` を指しているのかもしれない。

---

`apps/nano_planner/lib/nano_planner_web/controllers/plan_item_controller.ex` のファイルに新規追加した行
```
  def new(conn, _params) do
    plan_item = Schedule.build_plan_item()
    changeset = Schedule.change_plan_item(plan_item)
    render(conn, "new.html", changeset: changeset)
  end
```

**Comment by kuroda** [comment]
`mix compile` で次のようなエラーが出た。

```
== Compilation error in file lib/nano_planner_web/views/plan_item_view.ex ==
** (UndefinedFunctionError) function Phoenix.LiveView.HTMLEngine.compile/2 is undefined (module Phoenix.LiveView.HTMLEngine is not available)
    Phoenix.LiveView.HTMLEngine.compile("lib/nano_planner_web/templates/plan_item/new.html.heex", "new.html")
    (phoenix 1.5.14) lib/phoenix/template.ex:352: Phoenix.Template.compile/3
    (phoenix 1.5.14) lib/phoenix/template.ex:167: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.5.14) expanding macro: Phoenix.Template.__before_compile__/1
    lib/nano_planner_web/views/plan_item_view.ex:1: NanoPlannerWeb.PlanItemView (module)
    (elixir 1.11.4) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

これは、`apps/nano_planner/lib/nano_planner_web/templates/plan_item/new.html.heex` の拡張子を `.eex` に変更すればOK。
