### ISSUE TITLE
mix phx.server でエラーが出る

### ISSUE THREAD

**Issue by yui15** [yui15/nano_planner#3]
```
Node.js v18.17.1
[error] Task #PID<0.521.0> started from NanoPlannerWeb.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix 1.5.14) lib/phoenix/endpoint/watcher.ex:56: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14.2.3) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["node", ["node_modules/webpack/bin/webpack.js", "--mode", "development", "--watch-stdin", {:cd, "/apps/nano_planner/assets"}]]

webpack is watching the files…

[hardsource:2279df90] Using 0 MB of disk space.
[hardsource:2279df90] Writing new cache 2279df90...
[hardsource:2279df90] Tracking node dependencies with: package-lock.json.
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/apps/nano_planner/assets/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/apps/nano_planner/assets/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/apps/nano_planner/assets/node_modules/webpack/lib/NormalModule.js:471:10)
    at /apps/nano_planner/assets/node_modules/webpack/lib/NormalModule.js:503:5
    at /apps/nano_planner/assets/node_modules/webpack/lib/NormalModule.js:358:12
    at /apps/nano_planner/assets/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/apps/nano_planner/assets/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/apps/nano_planner/assets/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /apps/nano_planner/assets/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/apps/nano_planner/assets/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /apps/nano_planner/assets/node_modules/babel-loader/lib/index.js:44:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by kuroda** [comment]
`apps/nano_planner/config/dev.exs:18-32` を次のように書き換えてください（29-30が変更箇所）。

```elixir
config :nano_planner, NanoPlannerWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__),
      env: [{"NODE_OPTIONS", "--openssl-legacy-provider"}]
    ]
  ]
```
