### ISSUE TITLE
[ch11] モバイル版で予定項目の削除ボタンを押すとエラー

### ISSUE THREAD

**Issue by yui15** [yui15/nano_planner#4]
モバイル版で予定表を開き、ごみ箱アイコンをタップして予定項目を削除しようとすると、エラーが発生する。

【エラー内容】
```
 ** (Phoenix.Router.NoRouteError) no route found for DELETE /plan_items/3/edit (NanoPlannerWeb.Router)
    (nano_planner 0.1.0) lib/phoenix/router.ex:402: NanoPlannerWeb.Router.call/2
    (nano_planner 0.1.0) lib/nano_planner_web/endpoint.ex:1: NanoPlannerWeb.Endpoint.plug_builder_call/2
```

**Comment by yui15** [comment]
`mix ecto.reset` を行ったら解決。
