### ISSUE TITLE
[ch4] 「今日の予定表」を選択するとエラー

### ISSUE THREAD

**Issue by yui15** [yui15/nano_planner#9]
エラー内容
```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.apply("of_today.html", :private, [])
        (phoenix 1.5.14) lib/phoenix/controller.ex:242: Phoenix.Controller.action_name/1
        (phoenix 1.5.14) lib/phoenix/controller.ex:635: Phoenix.Controller.render/2
        (nano_planner 0.1.0) lib/nano_planner_web/controllers/plan_item_controller.ex:1: NanoPlannerWeb.PlanItemController.action/2
        (nano_planner 0.1.0) lib/nano_planner_web/controllers/plan_item_controller.ex:1: NanoPlannerWeb.PlanItemController.phoenix_controller_pipeline/2
```

**Comment by yui15** [comment]
【エラーが起きた原因】
- `index.html.eex` に `_index_row.html` を部分テンプレートとして埋め込んだ
- `index.html.eex` に `_delet_confirmation.html` を部分テンプレートとして埋め込んだ

**Comment by yui15** [comment]
【原因】
render した `of_today.html` がまだ未実装だったため。
